# Generated by Django 4.0 on 2022-11-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.CharField(max_length=200, null=True)),
                ('comentario', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('telefono', models.BigIntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('telefono', models.BigIntegerField()),
                ('descripcionNegocio', models.CharField(max_length=200)),
                ('calificacion', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('calificacion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.calificacion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.estadopedido')),
                ('productos', models.ManyToManyField(to='sistemadecompra.Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('mensaje', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('dia', models.CharField(max_length=15)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
