# Generated by Django 4.0.5 on 2022-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproductos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
