# Generated by Django 4.0.5 on 2022-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='calificacion',
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
