# Generated by Django 4.0.5 on 2022-06-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
