# Generated by Django 4.0.5 on 2022-11-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sistemadecompra.pedido')),
            ],
        ),
    ]
