# Generated by Django 4.0.5 on 2022-11-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0002_remove_proveedor_calificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='producto',
            name='imageUrl',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
