# Generated by Django 4.0 on 2022-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0003_remove_calificacion_fecha_producto_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='sistemadecompra.Producto'),
        ),
    ]
