# Generated by Django 4.0.5 on 2022-11-15 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistemadecompra', '0004_alter_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='pedido',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
