# Generated by Django 4.0 on 2022-12-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0004_alter_pedido_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imageUrl',
            new_name='imagenUrl',
        ),
    ]
