# Generated by Django 4.0 on 2022-11-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0006_alter_notificacion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='sistemadecompra.Producto'),
        ),
    ]
