# Generated by Django 4.0 on 2022-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0006_alter_calificacion_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horaFinal',
            field=models.TimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaInicio',
            field=models.TimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
