# Generated by Django 4.0 on 2022-12-04 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0007_alter_horario_horafinal_alter_horario_horainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
