# Generated by Django 4.0.5 on 2022-11-17 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0007_alter_pedido_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.CharField(max_length=200, null=True)),
                ('comentario', models.CharField(max_length=500)),
                ('fecha', models.TimeField()),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistemadecompra.pedido')),
            ],
        ),
    ]
