# Generated by Django 4.0.5 on 2022-12-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0009_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagein',
            field=models.ImageField(blank=True, upload_to='uploads/productos'),
        ),
    ]
