# Generated by Django 4.0.5 on 2022-11-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0010_estadopedido_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregado',
        ),
    ]
