# Generated by Django 4.0.5 on 2022-12-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0010_producto_imagein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagein',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
