# Generated by Django 4.0.5 on 2022-12-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0011_rename_imagein_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
