# Generated by Django 4.0.5 on 2022-12-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadecompra', '0013_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='uploads/productos'),
        ),
    ]
